apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "infra.mongodb.labels" . | nindent 4 }}
spec:
  serviceName: mongodb
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        {{- include "infra.mongodb.labels" . | nindent 8 }}
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.mongodbSecretName | quote }}
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.mongodbSecretName | quote }}
                  key: password
          ports:
            - name: mongodb
              containerPort: {{ .Values.mongodb.containerPort }}
          resources:
            {{- toYaml .Values.mongodb.resources | nindent 12 }}
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
        labels:
          {{- include "infra.mongodb.labels" . | nindent 10 }}
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if .Values.mongodb.persistence.storageClass }}
        storageClassName: {{ .Values.mongodb.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.mongodb.persistence.size | quote }}
