{{- if .Values.mongodb.auth.createSecret }}
{{- $password := required "Supply infra.mongodb.auth.password externally when createSecret=true" .Values.mongodb.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.mongodbSecretName | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "infra.mongodb.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.mongodb.auth.username | quote }}
  password: {{ $password | quote }}
  uri: {{ printf "mongodb://%s:%s@mongodb:%v/%s?authSource=admin" (.Values.mongodb.auth.username | urlquery | replace "+" "%20") ($password | urlquery | replace "+" "%20") .Values.mongodb.containerPort (.Values.mongodb.auth.database | urlquery | replace "+" "%20") | quote }}
{{- end }}
