apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend-report.fullname" . }}-conf
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend-report.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.containerPort | quote }}
